### ISSUE TITLE
Readme and Website

### ISSUE THREAD

**Issue by Wikunia** [WillSullivan/IDownvotedYouBecause#2]
Hi,

I saw your stackexchange "question" and was interested but there are some things that can  improved:
- Every repo needs a readme
- Is there an easy way to contribute? Like a template where I can add my downvote reasons? 
- Looks like there is no link from a reason or the list of reasons back to the home page.

**Comment by WillSullivan** [comment]
Point 1 is easy, I'll copy the question (with a little edit) into a readme.md.

Point two is something I'll work on in time.  I'd love to have a simple editor where people can use markdown to write the article, but that doesn't exist as of yet.  I'll create an issue for that separate to this issue.

The third point, meh.  The reason should really only link to the homepage AKA the about page. Typical users viewing a reason either can use the back button (those reviewing a reason) or have no need to go directly to the list of all reasons (the downvoted). The downvoted may wish to learn more about the website, so a link to an about page (currently the front page) is warranted.  I won't fix that.
