### ISSUE TITLE
SO - Image of an exception enhancement: Text in images isn't indexed

### ISSUE THREAD

**Issue by Aralun** [WillSullivan/IDownvotedYouBecause#7]
Just a small enhancement for `so/ImageOfAnException`:

> Text in images isn't indexed, so it is very hard if not impossible to find the question via search engines. It reduces the visibility of your question and prevents future readers from finding it.

**Comment by WillSullivan** [comment]
Updated, thanks.

**Comment by Aralun** [comment]
Nice note on screen readers!
