### ISSUE TITLE
Overlap of bullet point links and "Project maintained by"

### ISSUE THREAD

**Issue by Phrancis** [WillSullivan/IDownvotedYouBecause#8]
I was browsing the [AllTheReasons](http://idownvotedyoubecause.com/AllTheReasons) page and I noticed after opening the following links from the list:

> ### StackOverflow
> - [Image of an Exception](http://idownvotedyoubecause.com/so/ImageOfAnException) You pasted an image of your exception, not your exception
> - [No code](http://idownvotedyoubecause.com/AllTheReasons) Your question is about a bug, but you included no code
> - [No Exception details](http://idownvotedyoubecause.com/so/NoExceptionDetails) You said there was an Exception, but you didn't include it
> - [Too much code](http://idownvotedyoubecause.com/so/TooMuchCode) Your question is a hard to read code dump

I noticed all sections except "No code" section have the last bullet point link overlap with the "Project maintained by" section. That section has the fewest bullet points of all which explains why it displays "correctly". 

Screenshot showing the problem:

![screen shot 2016-03-21 at 1 06 35 am](https://cloud.githubusercontent.com/assets/8539648/13911012/65b788fa-ef01-11e5-9a0f-ff35d1a6a03e.png)

Screenshot showing the problem is not made apparent due to fewer bullet points. Ideally, the bottom edge of the bullet points should "push down" the other elemtn. 

![screen shot 2016-03-21 at 1 14 48 am](https://cloud.githubusercontent.com/assets/8539648/13911109/7e4b33fc-ef02-11e5-94ef-2417abc805e9.png)

**Comment by WillSullivan** [comment]
Thanks, will tweak.  
[edit] Hmmm, the liners at the bottom are positioned absolutely at the bottom, and the text is just flowing over as the window height isn't big enough to accommodate.  I could reduce the font size for the bullet points, I suppose....

**Comment by WillSullivan** [comment]
I'm closing this because the site is being migrated to idownloadedbecause.com, which will include a new skinning of the website.
